name: Github Action Hello World
on: [push]
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Olah Fernando!!!"
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: List files
        run: ls ${{github.workspace}}
